sudo: false
language: javascript
script:
- npm install
notifications:
  email:
    recipients:
    - travisci@fabrizio-branca.de
    on_success: always
    on_failure: always
before_deploy:
- ls
- zip --verbose -r index.zip index.js node_modules/
deploy:
  provider: releases
  api_key:
    secure: THhqZddQn/0rJTNOqbCGegKawrSSYA/YiFPXRVX5o/8NRKnH58NeFsIssCrSQY6C6agfHP4fLmlons/NXTyr0RgjmoRV7o/Fe8dJbipK5DNL4800U/uOwXDgveT03ehXKRfGpR8BR+Dw6GCzCBIezgMwjbbaAGVNGah/RfO46yfqJYVICYT6zeYF3ZFLZAEZGW8DcxWV5Jv11clspZx7Hzmf3uf9xKbta2B/eI7BSGs7t29TMmvRP0xRS9UpJxtosczXzXIREzZ0PuyPdZrcld+0/yXJwUpIDgC+cfmxDK6JCVqYyUCoj4UK4OaCvOEJL93Li7oiufY2tfuBrW7vfcGSjaPw6ZgWmdvm7OHaqmhmIQ98e6ZnrO/8qJZqeM8ChvSzrWpXglBwEVAdG8iv8QDL+TVe7/letvnA9aB8mLJ0baLfvY/ujTbx+UlnJdo7k5i4nJ/vaf/vbdEqdlYHF26I02NnOrlbhDInvCExUw0eRcs7uRN/avF5VO1aQ7Xhe8r0tY9f6OAIYMVI9VUDXOZwgcViuAsMVCyKwjYnMbUVnm0FMPiaoxe1a28gPewKSmneJgwPmjka5/FH6NOKZLkBXid8Z7sTtbePl4yRvCgYDvVF5gGaF1Q/H4AUbuTsfr+g/GptDDMkeYk2hXF3XLzFWCnDy9o0O0UzUt3lkjo=
  file: index.zip
  on:
    repo: AOEpeople/cloudfront2elasticsearch
